package com.example.bbacr.ddw.content;

/**
 * Created by Zhouziwen .
 * 邮箱：1916973618@qq.com
 */
public interface Url {
    String base_url = "http://www.chinaddcat.com";
//    String base_url = "http://192.168.3.55";
    String GetKey = base_url + "/user/userLoginKey.json?";//获取key
    String Login = base_url + "/user/userLogin.json?";//获得key进行加密登陆
    String home_page = "http://118.89.51.87:8010";//首页
    String entranceC = base_url+"/entranceC/getEntrance.json?";//首页顶部
    String bannerC = base_url+"/bannerC/getBanner.json?";//轮播图
    String openSearchC = base_url+"/openSearchC/goodSuggest.json?keywords=18";//下拉提示
    String goodSearch = base_url+"/openSearchC/goodSearch.json?";//开放搜索
    String ddmGoodsC =base_url+"/ddmGoodsC/portalDetails.json?";//商品详情
    String guessYouLiveGoods =base_url+"/ddmGoodsC/guessYouLiveGoods.json";//猜你喜欢
    String portalDetails2 =base_url+"/ddmGoodsC/portalDetails2.json?";//图文详情
    String myFootMark =base_url+"/footMarkC/myFootMark.json?";//我的足迹
    String cleanFootMarK =base_url+"/footMarkC/cleanFootMarK.json?";//清空我的足迹
    String delFootMark =base_url+"/footMarkC/delFootMark.json?";//删除我的足迹
    String oneLevelCategory =base_url+"/goodsCategoryC/oneLevelCategory.json";//一级分类
    String twoLevelCategory =base_url+"/goodsCategoryC/twoLevelCategory.json?";//二级分类
    String threeLevelCategory =base_url+"/goodsCategoryC/type2.json?";//更多分类
    String myCollections =base_url+"/collectionsC/myCollections.json?";//我的收藏
    String cleanCollections =base_url+"/collectionsC/cleanCollections.json?";//清空收藏
    String delCollections =base_url+"/collectionsC/delCollections.json?";//删除我的收藏
    String addCollections =base_url+"/collectionsC/addCollections.json?";//添加到我的收藏
    String getUserAddress =base_url+"/user/getUserAddress.json?";//地址列表
    String getDefault =base_url+"/user/getDefault.json?";//默认地址
    String userAddressToBeDefault =base_url+"/user/userAddressToBeDefault.json?";//指定默认收货地址
    String deleteUserAddress =base_url+"/user/deleteUserAddress.json?";//删除收货地址
    String editUserAddress =base_url+"/user/editUserAddress.json?";//编辑收货地址
    String addUserAddress =base_url+"/user/addUserAddress.json?";//添加收货地址
    String addComments =base_url+"/commentsC/addComments.json?";//添加评论
    String commentsSumdatas =base_url+"/commentsC/commentsSumdatas.json?";//获取评论统计
    String getCommentsList =base_url+"/commentsC/getCommentsList.json?";//评论列表
    String addUserShoppingCart =base_url+"/ShoppingCartC/addUserShoppingCart.json?";//添加购物车
    String buyRightNow =base_url+"/purchaseOrderC/buyRightNow.json?";//立即购买
    String cartsBuy =base_url+"/purchaseOrderC/cartsBuy.json?";//去结算
    String submitOrder =base_url+"/purchaseOrderC/submitOrder.json?";//提交订单
    String getUserShoppingCart =base_url+"/ShoppingCartC/getUserShoppingCart.json?";//查询购物车
    String modifyUserShoppingCart =base_url+"/ShoppingCartC/modifyUserShoppingCart.json?";//修改购物车
    String optionCart =base_url+"/ShoppingCartC/optionCart.json?";//勾选购物车
    String allSelect =base_url+"/ShoppingCartC/allSelect.json?";//全选购物车
    String deleteUserShoppingCart =base_url+"/ShoppingCartC/deleteUserShoppingCart.json?";//删除购物车
    String modifyCount =base_url+"/ShoppingCartC/modifyCount.json?";//增加数量
    String getSpecification =base_url+"/specificationC/getSpecification.json?";//规格
    String getGoodSpecification =base_url+"/goodSpecificationC/getGoodSpecification.json?";//规格详情
    String getGoodsValueAddedServices =base_url+"/ddmGoodsC/getGoodsValueAddedServices.json?";//增值服务
    String getPriceRecord =base_url+"/ddmGoodsC/getPriceRecord.json?";//价格走势
    String getUserHeadData =base_url+"/user/getUserHeadData.json?";//个人中心
    String getUserId =base_url+"/user/getUserId.json?";//得到使用者的id
    String QRCODEC = "/qrcodeC/authorize/";//获取用户邀请码
    String getUserMessages = base_url +"/messagesC/getUserMessages.json?";//用户消息
    String getOneMessages = base_url +"/messagesC/getOneMessages.json?";//获得用户消息详情
    String updateNotReadMessages = base_url +"/messagesC/updateNotReadMessages.json?";//修改消息为已读
    String uploadImage = base_url +"/uploadImage.do";//上传图片
    String updateAvtor = base_url +"/user/updateAvtor.json?";//上传图片
    String shareTeam = base_url +"/lowerC/shareTeam.json?";//分享团队
    String getCommission = base_url +"/commissionC/getCommission.json?";//分享流水
    String getDetailCommission = base_url +"/commissionC/getDetailCommission.json?";//分享流水详情
    String orderList = base_url +"/purchaseOrderC/orderList.json?";//订单列表
    String confirmReceiptOrder = base_url +"/purchaseOrderC/confirmReceiptOrder.json?";//确认收货
    String orderDetail = base_url +"/purchaseOrderC/orderDetail.json?";//订单详情
    String pay = base_url +"/balance/pay.json?";//余额支付
    String payApp = base_url +"/ali/payApp.json?";//支付宝支付
    String info = base_url +"/user/info.json?";//基本资料
    String userLoginKey = base_url + "/user/userLoginKey.json?";//获取key
    String updatePassword = base_url +"/user/updatePassword.json?";//修改登陆密码和交易密码
    String sendMobileCode_Vtoken = base_url +"/user/sendMobileCode_Vtoken.json?";//有token，获取验证码
    String sendMobileCode_v2 = base_url +"/user/sendMobileCode_v2.json?";//，获取验证码
    String checkCode_register = base_url +"/user/checkCode_register.json?";//完成注册
    String findPassword = base_url + "/user/findPassword.json?";//找回密码
    String updateBirthday = base_url +"/user/updateBirthday.json?";//修改生日
    String updateRealName = base_url +"/user/updateRealName.json?";//修改姓名
    String updateEmail = base_url +"/user/updateEmail.json?";//修改邮箱
    String updateWeixin = base_url +"/user/updateWeixin.json?";//修改微信
    String updateQQ = base_url +"/user/updateQQ.json?";//修改qq
    String purchaseOrderNum = base_url +"/purchaseOrderC/purchaseOrderNum.json?";//订单数量
    String searchUserCardsNum = base_url +"/userCardsC/searchUserCardsNum.json?";//我的优惠券数量
    String searchCards = base_url +"/cardsC/searchCards.json?";//优惠券列表
    String MyCard = base_url +"/userCardsC/searchCards.json";//我的优惠券列表
    String getCards = base_url +"/userCardsC/getCards.json?";//领取优惠券
    String searchService = base_url +"/serviceOrderC/searchService.json?";//电子保修卡
    String getPortalShopList = base_url +"/ddmShopC/getPortalShopList.json?";//到店自取
    String Alter_Sex = base_url + "/user/updateSex.json?";//修改性别
    String VERSION = base_url +"/user/appVersion.json";//判断版本号
    String UPDAPE = base_url +"/zl.apk";//更新
    String cancelOrder = base_url +"/purchaseOrderC/cancelOrder.json?";//取消整个
    String stopOrder = base_url +"/purchaseOrderC/stopOrder.json?";//取消一个
    String orderComment = base_url +"/purchaseOrderC/orderComment.json?";//去评价商品
    String refundList = base_url +"/purchaseOrderC/refundList.json?";//退款
    String refundDetail = base_url +"/purchaseOrderC/refundDetail.json?";//退款详情
    String cancelRefund = base_url +"/purchaseOrderC/cancelRefund.json?";//撤销
    String refundApply = base_url +"/purchaseOrderC/refundApply.json?";//售后申请
    String popSearch = base_url +"/openSearchC/popSearch.json";//热门搜索
    String OAuth = base_url +"/OAuth/OAuthIsRegist3.json?";//是否为注册过的用户
    String OAuthNewRegist = base_url +"/OAuth/OAuthNewRegist.json?";//新用户注册并绑定
    String OAuthOldRegist = base_url +"/OAuth/OAuthOldRegist.json?";//老用户注册并绑定
    String getUserFmsFlowV1 = base_url + "/flowC/getUserFmsFlowV1.1.json?";//资金流水
    String getTiXianFactorage = base_url + "/tiXianC/getTiXianFactorage.json?";//提现详情
    String getCardList = base_url + "/cardC/getCardList.json?";//获取银行卡
    String addTiXianShenQing = base_url + "/tiXianC/addTiXianShenQing.json?";//积分兑换
    String userGetTiXianShenQingList = base_url + "/tiXianC/userGetTiXianShenQingList.json?";//兑换明细
    String toBeDefault = base_url + "/cardC/toBeDefault.json?";//指定银行卡为默认银行卡
    String addCard = base_url + "/cardC/addCard.json?";//添加银行卡
}
